spring:
  application:
    name: spring-security
  jpa:
    # Provide database platform that is being used
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      # New database is created when application starts and destroyed when application is stopped
      ddl-auto: update
    # Show sql when spring data jpa performs query
    show-sql: true
    properties:
      hibernate:
        # Format queries
        format_sql: true
  flyway:
    enabled: false
    baseline-on-migrate: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  sql:
    init:
      platform: postgres
token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351